# Generated by Django 4.2.7 on 2023-11-07 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('prerequisites', models.TextField()),
                ('syllabus', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enrollment_limit', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('medical_school', models.CharField(max_length=100)),
                ('completed_courses', models.ManyToManyField(related_name='students_completed_courses', to='lmsapp.course')),
                ('enrolled_courses', models.ManyToManyField(related_name='students_enrolled_courses', to='lmsapp.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('completed_modules', models.ManyToManyField(related_name='student_completed_modules', to='lmsapp.course')),
                ('courses', models.ManyToManyField(related_name='student_courses', to='lmsapp.course')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_degree', models.CharField(max_length=100)),
                ('specialization', models.TextField()),
                ('courses_taught', models.ManyToManyField(related_name='instructor_courses_taught', to='lmsapp.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.instructorprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='students_completed',
            field=models.ManyToManyField(related_name='courses_completed', to='lmsapp.studentprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(related_name='courses_enrolled', to='lmsapp.studentprofile'),
        ),
        migrations.CreateModel(
            name='AdministratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
