# Generated by Django 4.2.7 on 2023-11-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='degree_program',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
