# Generated by Django 5.0 on 2023-12-23 01:52

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_studentprofile_degree_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratorprofile',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='objectives',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_completed', to='lmsapp.studentprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_enrolled', to='lmsapp.studentprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='courses_taught',
            field=models.ManyToManyField(blank=True, null=True, related_name='instructor_courses_taught', to='lmsapp.course'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='specialization',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_completed_courses', to='lmsapp.course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_enrolled_courses', to='lmsapp.course'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_completed_modules', to='lmsapp.course'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_courses', to='lmsapp.course'),
        ),
    ]
