# Generated by Django 5.0 on 2023-12-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_doctor_physician_rename_owner_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='I am yet to write a post...', help_text='You can write your posts here'),
        ),
    ]
