# Generated by Django 5.0.4 on 2024-04-11 00:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='N', max_length=2)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.TextField()),
                ('address', models.TextField()),
                ('town', models.CharField(default='Prefer not to sat', max_length=100)),
                ('state', models.CharField(default='Prefer not to say', max_length=100)),
                ('skills', models.CharField(default='Coding', max_length=200)),
                ('hobbies', models.CharField(default='Swimming', max_length=200)),
                ('publications', models.TextField(help_text='Please provide the necessary details such as the title,year and author(s) of publication ')),
                ('official_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ur', 'Urdu'), ('tr', 'Turkish'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('fi', 'Finnish')], default='en', max_length=2)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('working_hours', models.TextField()),
                ('bio', models.TextField()),
                ('awards_and_recognitions', models.TextField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('is_board_certified', models.BooleanField(default=False)),
                ('license_number', models.CharField(max_length=20, null=True)),
                ('average_rating', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('available_for_consultation', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=2, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('hospitals', models.ManyToManyField(blank=True, to='doctorapi.hospital')),
                ('insurance_companies', models.ManyToManyField(blank=True, to='doctorapi.insurancecompany')),
                ('medical_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapi.medicalschool')),
            ],
        ),
    ]
