# Generated by Django 4.2.6 on 2023-10-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hobbies',
            field=models.CharField(default='Swimming', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='skills',
            field=models.CharField(default='Coding', max_length=200),
        ),
    ]
