# Generated by Django 4.2.6 on 2023-10-29 18:41

import ckeditor.fields
from django.db import migrations, models
import django_countries.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('doctorapi', '0002_doctor_hobbies_doctor_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_for_consultation',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='awards_and_recognitions',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_hours',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
