# Generated by Django 5.0 on 2023-12-22 04:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0004_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='publications',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
