# Generated by Django 5.0 on 2023-12-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0005_alter_doctor_publications_delete_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='publications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapi.publication'),
        ),
    ]
