# Generated by Django 5.0 on 2023-12-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0006_publication_alter_doctor_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='languages_spoken',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_spoken',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ur', 'Urdu'), ('tr', 'Turkish'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('fi', 'Finnish')], default='en', max_length=2),
        ),
    ]
