# Generated by Django 5.0 on 2023-12-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0007_remove_doctor_languages_spoken_delete_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='publications',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_affiliations',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
