# Generated by Django 5.0 on 2023-12-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0008_alter_doctor_publications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_for_consultation',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='publications',
            field=models.TextField(help_text='Please provide the necessary details such as the title,year and author(s) of publication '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='Prefer not to say', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='town',
            field=models.CharField(default='Prefer not to sat', max_length=100),
        ),
    ]
