# Generated by Django 5.0 on 2023-12-23 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0011_doctor_city_doctor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='average_rating',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
