# Generated by Django 5.0 on 2023-12-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0012_alter_doctor_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
