# Generated by Django 5.0 on 2023-12-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0013_alter_doctor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_for_consultation',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=2, null=True),
        ),
    ]
