# Generated by Django 5.0 on 2023-12-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0014_alter_doctor_available_for_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='languages_spoken',
            new_name='official_language',
        ),
    ]
