# Generated by Django 4.2.4 on 2023-08-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicblog', '0002_alter_comments_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='body',
            field=models.TextField(default='Expect new comments soon...'),
        ),
    ]
